title: Edge Analytics Grafana Setup

social-network-links:
  twitter: 'https://twitter.com/System73PolyNet'
  youtube: 'https://www.youtube.com/@system7388'
  github: 'https://github.com/System73'
  linkedin: 'https://www.linkedin.com/company/system-73'

markdown: kramdown
theme: jekyll-theme-cayman
