services:

  grafana:
    image: grafana/grafana-oss:11.0.0
    environment:
      - TERM=xterm
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=system73-3dtopology-panel,system73-3dglobe-panel
      - GF_INSTALL_PLUGINS=https://github.com/grafana/grafana-json-datasource/releases/download/v1.3.16/marcusolsson-json-datasource-1.3.16.zip;marcusolsson-json-datasource, 
          https://cdn.s73cloud.com/grafana-plugin/system73-3dtopology-panel-1.4.1.zip;system73-3dtopology-panel,
          https://cdn.s73cloud.com/grafana-plugin/system73-3dglobe-panel-1.2.6.zip;system73-3dglobe-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - grafana-net
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/datasources/json-api.yaml:/etc/grafana/provisioning/datasources/json-api.yaml
      - ./provisioning/dashboards/ea-advanced-dashboard.json:/var/lib/grafana/dashboards/ea-advanced-dashboard.json
      - ./provisioning/dashboards/ea-basic-dashboard.json:/var/lib/grafana/dashboards/ea-basic-dashboard.json
    env_file: .env

networks:
  grafana-net:
