services:

  grafana:
    image: grafana/grafana-oss:11.0.0
    environment:
      - TERM=xterm
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=system73-3dtopology-panel,system73-3dglobe-panel
      - GF_INSTALL_PLUGINS=https://github.com/grafana/grafana-json-datasource/releases/download/v1.3.16/marcusolsson-json-datasource-1.3.16.zip;marcusolsson-json-datasource, 
          https://s73-grafana-artifacts.s3.eu-west-1.amazonaws.com/3d-plugins/system73-3dtopology-panel-1.4.2.zip;system73-3dtopology-panel,
          https://s73-grafana-artifacts.s3.eu-west-1.amazonaws.com/3d-plugins/system73-3dglobe-panel-1.2.6.zip;system73-3dglobe-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - grafana-net
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards/customer:/etc/grafana/provisioning/dashboards
    env_file: .env

  reseller-grafana:
    image: grafana/grafana-oss:11.0.0
    environment:
      - TERM=xterm
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=system73-3dtopology-panel,system73-3dglobe-panel
      - GF_INSTALL_PLUGINS=https://github.com/grafana/grafana-json-datasource/releases/download/v1.3.16/marcusolsson-json-datasource-1.3.16.zip;marcusolsson-json-datasource,
        https://github.com/grafana/grafana-infinity-datasource/releases/download/v3.0.0/yesoreyeram-infinity-datasource-3.0.0.zip;yesoreyeram-infinity-datasource,
        https://github.com/VolkovLabs/volkovlabs-env-datasource/releases/download/v4.1.0/volkovlabs-env-datasource-4.1.0.zip;volkovlabs-env-datasource,
        https://s73-grafana-artifacts.s3.eu-west-1.amazonaws.com/3d-plugins/system73-3dtopology-panel-1.4.2.zip;system73-3dtopology-panel,
        https://s73-grafana-artifacts.s3.eu-west-1.amazonaws.com/3d-plugins/system73-3dglobe-panel-1.2.6.zip;system73-3dglobe-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3001:3000"
    networks:
      - grafana-net
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards/reseller:/etc/grafana/provisioning/dashboards
    env_file: .env

networks:
  grafana-net:
